spring:
  application:
    name: Veridato-CTI
  datasource:
    url: jdbc:agensgraph://
    host: localhost
    # port: 5555
    port: 16666
    database: ctias
    username: ctias
    password: ctias
    graph-path: ctias
    driver-class-name: net.bitnine.agensgraph.Driver
    mongofdw: mongo_fdw
    mongoserver: mongo_server
  data:
    mongodb:
      host: 118.223.123.214
      port: 4101
      database: THREAT_GR
    
query:
  path: static/query/query.yml
  
server:
  tomcat:
    max-threads: 400
    accesslog:
      enabled: true
  port: 8080
#  port: 8080
      
veridato:
  product:
    name: Veridato-CTI
    version: 1.0
  cpool:
    setMinimumIdle: 10
    setMaximumPoolSize: 50
    
management:
  context-path: /monitor
  security:
    enabled: false

endpoints:
  cors:
    allowed-origins: '*'
    allowed-methods: GET,POST
    allowed-headers: '*'
    allow-credentials: false
    max-age: 3600

security:
  basic:
    enabled: false

cti:
  fdw:
    multicorn:
      basic:
        enabled: false
        
ctias:
  security:
    enabled: false
  attackpattern:
    list: intrusion_set,ip,domain,hash,filename,location
  
mongodb:
  basic:
    enabled: false

net:
  bitnine:
    veridato:
      scheduling:
        enabled: false