
###
POST http://localhost:8088/jsonrpc
Content-Type: application/json

{"jsonrpc":"2.0","method":"get_graph_stats","id":2}



###
POST http://localhost:8088/jsonrpc
Content-Type: application/json

{"jsonrpc":"2.0","method":"get_algorithms","id":1}



###
POST http://localhost:8088/jsonrpc
Content-Type: application/json

{"jsonrpc":"2.0","method":"stringer"}

###
