@startuml
:데이타전문가: as da
:보안분석가: as sa
:일반사용자: as user

(domain graph를 탐색한다.) as (exp)
(탐색 pattern 을 관리한다.) as (m_ptn)
(pattern 으로 graph를 탐색한다.) as (p_exp)
(domain graph에 알고리즘을 적용한다.) as (alg)
(알고리즘을 관리한다) as (m_alg)

da ---> (기존데이타를 domain graph로 변환한다.)

sa -right-> (exp)
sa ---> (alg)
sa --> (m_ptn)
sa -> (m_alg)


user -down-> (p_exp)
user -> (exp)

@enduml