
#### value 검색 시 해당하는 레이블 조회 (하이라이팅 기능을 위함)
GET http://localhost:3000/api/proto/keyword?value=HornePrince178
Accept: application/json, application/hal+json

####
GET http://localhost:3000/api/proto/keyword?value=ddd
Accept: application/json, application/hal+json

#### Metagraph 조회
GET http://localhost:3000/api/proto/metagraph
Accept: application/json, application/hal+json

#### Pattern 기반 조회 결과 그래프 데이터
POST http://localhost:3000/api/proto/graph
Accept: application/json, application/hal+json
Content-Type: application/json

[ { "id": "groups" },
  { "label": "in_group", "direction": "forward" },
  { "id": "email_message" },
  { "label": "sent", "direction": "forward" },
  { "id": "email_address" ,"filterFlag": true, "filterKeyword": "HornePrince1780@bankslawteam.com"} ]


###  path 로 리턴
POST http://localhost:3000/api/proto/graph_as_path
Accept: application/json, application/hal+json
Content-Type: application/json

[ { "id": "groups" },
{ "label": "in_group", "direction": "forward" },
{ "id": "email_message" },
{ "label": "sent", "direction": "forward" },
{ "id": "email_address" ,"filterFlag": true, "filterKeyword": "HornePrince1780@bankslawteam.com"} ]

###
POST http://localhost:3000/api/proto/graph_as_vertex
Accept: application/json, application/hal+json
Content-Type: application/json

[
  {
    "gtype":"vertex",
    "label": "ip",
    "params": [{ "name": "value", "comp": ",=", "value": "112.121.171.94" }]
  }
]

###
POST http://localhost:3000/api/proto/keyword
Accept: application/json, application/hal+json
Content-Type: application/json

{
   "keyword": "ddd"
}


###
POST http://localhost:3000/api/expand/all
Accept: application/json, application/hal+json
Content-Type: application/json

{
  "id": "3.640",
  "label": "ioc"
}

###
POST http://localhost:3000/api/bookmark/cg/list
Accept: application/json, application/hal+json
Content-Type: application/json

{
  "gid" : "3.259416",
  "user_id":"sglee"
}


#### Expand 기능
POST http://localhost:3000/api/proto/graph/expand
Accept: application/json, application/hal+json
Content-Type: application/json

{
  "label": "email_address",
  "id" : 11.253856
}


#### Expand info 조회 기능
POST http://localhost:3000/api/proto/graph/expand_summary
Accept: application/json, application/hal+json
Content-Type: application/json

{
  "label": "email_address",
  "id" : 11.253856
}

#### node meta stat select
POST http://localhost:3000/api/proto/graph/meta/stat
Accept: application/json, application/hal+json
Content-Type: application/json

{
  "label": "groups"
}


#### pattern similar
POST http://localhost:3000/api/pattern/similar
Accept: application/json, application/hal+json
Content-Type: application/json

{
  "pattern_str": "(:email_message)-[:rece]->()"
}


#### Pattern 기반 조회 결과 그래프 데이터
GET http://localhost:3000/api/proto/graph/domain/expand?label=domain&id=30.153590
Accept: application/json, application/hal+json

#### Pattern 기반 조회 결과 그래프 데이터
GET http://localhost:3000/api/proto/graph/ip/expand?label=ip&id=23.207276
Accept: application/json, application/hal+json

#### Pattern 기반 조회 결과 그래프 데이터
GET http://localhost:3000/api/proto/graph/url/expand?label=url&id=13.42
Accept: application/json, application/hal+json

#### Pattern 기반 조회 결과 그래프 데이터
GET http://localhost:3000/api/proto/graph/email/expand?label=url&id=13.42
Accept: application/json, application/hal+json

#### Pattern 기반 조회 결과 그래프 데이터
#### 성능이 안 좋아서 다른 방법 생각해봐야 함
GET http://localhost:3000/api/proto/graph/email/expand?label=email_address&id=11.293808
Accept: application/json, application/hal+json

#### custom group list 조회
GET http://localhost:3000/api/bookmark/cg/list
Accept: application/json, application/hal+json

#### bookmark 등록
#### gid , user_id , group_id
POST http://localhost:3000/api/bookmark/add
Accept: application/json, application/hal+json
Content-Type: application/json

{
  "gid": "23.194390",
  "user_id": "kisa",
  "group_id": 1
}

#### bookmark 등록
#### gid , user_id , group_id
POST http://localhost:3000/api/proto/ioc/vertex
Accept: application/json, application/hal+json
Content-Type: application/json

{
  "gid": "23.194390",
  "user_id": "kisa",
  "group_id": 1
}

###


