### 연세모두의원
POST https://partner.medilinx.co.kr/api/medilinx/v1/checkup/list
Content-Type: application/json
Authorization: Bearer cIZn1YacssssDQHNNE3bEZDphmg1FasKJ2FowXFUAomt4auQAJTnxfYBcX9iauS21bzlLSdhKCkqkCqQm9N1m0NIcfNpo2ji03WvWcCgQxBTBH8cUCXzKhXWOeBbojBD44OfuFHBJ6fsGviXOc9WZQ==

{
  "hosId": "E117F9D32AD5B488E75A9FDF530EE63122E66554592DEF07DEF3BD22DDE4CB4A",
  "startDate": "20220401",
  "endDate": "20220430"
}




### 삼성탑내과(종합)
POST https://partner.medilinx.co.kr/api/medilinx/v1/checkup/list
Content-Type: application/json
Authorization: Bearer ﻿cIZn1YacssssDQHNNE3bEZDphmg1FasKJ2FowXFUAomLE7QWyDg185nuNEn9qci5GhEy3jvr08ym/KCmwK9Q9OEQwGmmwb042j0jasXE47ww3Va4UDcHPnQkpWkxwjdh7hSOuaJT6vN6ele7By4BLA==

{
  "hosId": "087AD5C09CEED97F82094AACEE4A8A7AF8F09B2C4EE781C3AD1613DD240768BA",
  "startDate": "20220401",
  "endDate": "20220430"
}



### 삼성탑내과(종합)
POST https://partner.medilinx.co.kr/api/medilinx/v1/checkup/list
Content-Type: application/json
Authorization: Bearer ﻿cIZn1YacssssDQHNNE3bEZDphmg1FasKJ2FowXFUAomLE7QWyDg185nuNEn9qci5GhEy3jvr08ym/KCmwK9Q9OEQwGmmwb042j0jasXE47ww3Va4UDcHPnQkpWkxwjdh7hSOuaJT6vN6ele7By4BLA==

{
  "hosId": "087AD5C09CEED97F82094AACEE4A8A7AF8F09B2C4EE781C3AD1613DD240768BA",
  "startDate": "20220401",
  "endDate": "20220430"
}