export const graphData = {
  nodes: [
    { id: 1, label: 'worker', name: '전현수', radius: 8 },
    { id: 2, label: 'organization', name: '뱅크웨어글로벌' },
    { id: 3, label: 'organization', name: '비트나인' },
    { id: 4, label: 'organization', name: '인사이드정보' },
    { id: 5, label: 'organization', name: '티피소프트코리아' },
    { id: 6, label: 'organization', name: '피어나인' },
  ],
  edges: [
    { source: 1, target: 2 },
    { source: 1, target: 3 },
    { source: 1, target: 4 },
    { source: 1, target: 5 },
    { source: 1, target: 6 },
  ],
};

export const expandedData = {
  nodes: [
    { id: 7, label: 'skill', name: 'Java', radius: 10, color: 'orange' },
    { id: 8, label: 'skill', name: 'Javascript', radius: 10, color: 'orange' },
    { id: 9, label: 'skill', name: 'Typescript', radius: 10, color: 'orange' },
    { id: 10, label: 'skill', name: 'Python', radius: 10, color: 'orange' },
    { id: 11, label: 'skill', name: 'GraphDB', radius: 10, color: 'orange' },
    { id: 12, label: 'skill', name: 'Oracle', radius: 10, color: 'orange' },
    { id: 13, label: 'skill', name: 'Node.js', radius: 10, color: 'orange' },
    { id: 14, label: 'skill', name: 'Nest.js', radius: 10, color: 'orange' },
    { id: 15, label: 'skill', name: 'GraphQL', radius: 10, color: 'orange' },
    { id: 16, label: 'skill', name: 'Prisma', radius: 10, color: 'orange' },
    { id: 17, label: 'skill', name: 'React', radius: 10, color: 'orange' },
    { id: 18, label: 'skill', name: 'Elasticsearch', radius: 10, color: 'orange' },
    { id: 19, label: 'skill', name: 'Redis', radius: 10, color: 'orange' },
    { id: 20, label: 'skill', name: 'React-Native', radius: 10, color: 'orange' },
  ],
  edges: [
    { source: 4, target: 7 },
    { source: 4, target: 12 },
    { source: 3, target: 7 },
    { source: 3, target: 11 },
    { source: 3, target: 8 },
    { source: 3, target: 12 },
    { source: 3, target: 17 },
    { source: 3, target: 10 },
    { source: 3, target: 13 },
    { source: 2, target: 10 },
    { source: 2, target: 12 },
    { source: 5, target: 7 },
    { source: 5, target: 8 },
    { source: 5, target: 10 },
    { source: 5, target: 18 },
    { source: 5, target: 19 },
    { source: 5, target: 13 },
    { source: 5, target: 17 },
    { source: 6, target: 7 },
    { source: 6, target: 8 },
    { source: 6, target: 9 },
    { source: 6, target: 17 },
    { source: 6, target: 12 },
    { source: 6, target: 13 },
    { source: 6, target: 14 },
    { source: 6, target: 15 },
    { source: 6, target: 16 },
    { source: 6, target: 20 },
  ],
};
