project:
  location: remote
db:
  seoul:
    max_connection: 10
    min_connection: 5
    db_host: 192.168.0.68
    db_port: 5555
    db_name: ctias
    db_user: ctias
    graph_path: ctias
  remote:
    max_connection: 10
    min_connection: 5
    db_host: localhost
    db_port: 5432
    db_name: ctias
    db_user: ctias
    graph_path: ctias